---
driver:
  name: docker
  #name: vagrant
  use_sudo: false


platforms:
  - name: fedora-26


provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  require_ansible_omnibus: false
  ansible_version: 'latest'

  ansible_diff: true
  ansible_verbose: true
  require_chef_for_busser: false

  ansible_inventory: 'tests/inventory'
  additional_copy_path:
    - 'ansible/host_vars'
    - 'playbooks'
    - 'tasks'

  # Ansible fails if it can't decoded secrets.
  # Passing different secrets for prod/test and managing
  # the test secret is a pain so just delete the vaults.
  custom_pre_play_command: |
    echo 'Deleting vault files ...'
    rm -v /tmp/kitchen/host_vars/m910q/vault_*
    echo 'Done deleting vaults'
    echo 'Installing extra system packages ...'
    sudo dnf install -y cronie 'dnf-command(copr)' procps-ng findutils
    echo 'Done extending system'

  requirements_path: 'requirements.yml'
  hosts: ['localhost']


verifier:
  name: serverspec
  use_sudo: false
  #sudo_path: true

suites:
  - name: task
    provisioner:
      playbook: 'tests/task.yml'
      extra_vars:
        task_to_test: 'runtime/nodejs.yml'

  - name: play
    provisioner:
      playbook: 'tests/play.yml'
      extra_vars:
        playbook_to_test: 'playbooks/app/authgateway.yml'
        #playbook_to_test: 'playbooks/infra/datastores.yml'
        #playbook_to_test: 'playbooks/infra/monitoring.yml'
        #playbook_to_test: 'playbooks/infra/system.yml'

        # Backup extra vars.
        vault_backups_aws_key: 'key'
        vault_backups_aws_secret: 'secret'

        # Common extra vars.
        vault_me_email: 'test@example.com'

        # Email extra vars.
        email_inet_protocols: 'ipv4'
        vault_email_relay_user: 'ses-user'
        vault_email_relay_password: 'ses-passwd'

        # AuthGateway extra vars.
        upstream_nginx_service_manage: false
        vault_authgateway_client_id: 'abc'
        vault_authgateway_client_secret: 'def'
        vault_authgateway_session_secret: 'egh'
        vault_authgateway_allowed_emails: ['test@example.com']

        # Monitoring extra vars.
        vault_grafana_admin_user: admin
        vault_grafana_admin_password: admin
        vault_grafana_secret_key: 1234
