# My roles.
- src: stefano-pogliani.upstream-nginx
  version: v0.0.3
- src: stefano-pogliani.authgateway
  version: v0.2.1

  # Other people's roles.
- src: nickhammond.logrotate
  # Can't version yet, master has no tag.
