#!/bin/bash
#  Wrapper to ansible-playbook to pass all the vault options.
ansible-playbook \
  --vault-id authgateway@.authgateway.vaultsecret \
  --vault-id backups-key@.backups-key.vaultsecret \
  --vault-id backups@.backups.vaultsecret \
  --vault-id email@.email.vaultsecret \
  --vault-id firefly-iii@.firefly-iii.vaultsecret \
  --vault-id grafana@.grafana.vaultsecret \
  --vault-id me@.me.vaultsecret \
  --verbose \
  --become --ask-become-pass \
  "$@"
