#!/bin/bash
#  Wrapper to ansible to pass all the vault options.
ansible \
  --vault-id authgateway@.authgateway.vaultsecret \
  --vault-id email@.email.vaultsecret \
  --vault-id grafana@.grafana.vaultsecret \
  --vault-id me@.me.vaultsecret \
  --verbose \
  --become --ask-become-pass \
  "$@"

