---
- name: MongoDB | Configure Official Repo
  yum_repository:
    baseurl: 'https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.4/x86_64/'
    description: mongodb-org
    enabled: yes
    file: mongodb-org
    gpgcheck: yes
    gpgkey: 'https://www.mongodb.org/static/pgp/server-3.4.asc'
    name: mongodb-org
    repo_gpgcheck: yes
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'
    sslverify: yes

- name: MongoDB | Install package
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'mongodb-org-server'
    - 'mongodb-org-shell'
    - 'mongodb-org-tools'
  notify:
    - Restart MongoDB
