---
- name: FireFly-III | Render dockerfile
  copy:
    dest: '/data/firefly-iii/{{ item }}'
    group: 'firefly-iii'
    mode:  0644
    owner: 'firefly-iii'
    src: '{{ item }}'
  with_items:
    - 'Dockerfile'
    - 'entrypoint-override.sh'

- name: FireFly-III | Render VirtualHost
  template:
    dest:  '/data/firefly-iii/000-default.conf'
    src:   '000-default.conf'
    group: 'firefly-iii'
    mode:   0644
    owner: 'firefly-iii'

- name: FireFly-III | Build image
  docker_image:
    buildargs:
      GROUP_ID: '{{ firefly_group_id }}'
      USER_ID:  '{{ firefly_user_id }}'
      LISTEN_ADDRESS: '{{ firefly_listen_address }}'
      LISTEN_PORT: '{{ firefly_listen_port }}'
    name: 'firefly-iii'
    path: '/data/firefly-iii'
    rm: true
    state: present
    tag: '4.7.14'
  when: 'not("/.dockerenv" is exists)'
