---
- name: Backups | GoF3r | Fetch archives
  get_url:
    url: 'https://github.com/rlmcpherson/s3gof3r/releases/download/v0.5.0/gof3r_0.5.0_linux_amd64.tar.gz'
    dest: '/opt/backups/archives/gof3r_0.5.0_linux_amd64.tar.gz'
    checksum: 'sha256:d88f199d1580d8c8cac26ba39e15dc6e2126d20e56c3894bd37a226e8b3e665c'
    mode: 0644

- name: Backups | GoF3r | Extract the release
  unarchive:
    remote_src: yes
    dest: '/opt/backups/bin'
    src: '/opt/backups/archives/gof3r_0.5.0_linux_amd64.tar.gz'

- name: Backups | GoF3r | Activate the current version
  file:
    path: '/opt/backups/bin/gof3r'
    src: '/opt/backups/bin/gof3r_0.5.0_linux_amd64/gof3r'
    state: link
