---
- name: Backups | Create needed directories
  file:
    path: '/opt/{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - 'backups'
    - 'backups/archives'
    - 'backups/bin'
    - 'backups/mnt'

- name: Backups | GoF3r | Install
  import_tasks: 'gof3r.yml'

- name: Backups | Render AWS Secrets
  template:
    dest: '/opt/backups/secrets'
    mode: 0600
    src: 'secrets'

- name: Backups | Render Backups Encryption Secrets
  copy:
    # Only decrypt outside of Kitchen
    decrypt: '{{ not("/.dockerenv" is exists) }}'
    dest: '/opt/backups/backups.key'
    mode: 0400
    src: 'backups.key'

- name: Backups | Render Snapshost Script
  copy:
    dest: '/opt/backups/snapshot.sh'
    mode: 0750
    src: 'snapshot.sh'

- name: Backups | CronJob
  copy:
    dest: '/etc/cron.d/backups'
    mode: 0644
    content: |
      SHELL=/bin/sh
      PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      MAILTO={{ backups_email }}
      16 2 * * * root /opt/backups/snapshot.sh
