---
- name: Grafana | Configure Repo
  yum_repository:
    baseurl: 'https://packages.grafana.com/oss/rpm'
    description: grafana
    enabled: yes
    file: grafana
    gpgcheck: yes
    gpgkey: 'https://packages.grafana.com/gpg.key'
    name: grafana
    repo_gpgcheck: yes
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'
    sslverify: yes

- name: Grafana | Install package
  package:
    name: grafana
    state: present
  notify:
    - Restart Grafana
