---
- name: Prometheus | Server | Render systemd unit
  copy:
    dest:  '/etc/systemd/system/prometheus.service'
    src:   'prometheus.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart Prometheus

- name: Prometheus | Server | Configure Service
  systemd:
    daemon_reload: yes
    name: prometheus
    state: started
