---
- name: NTP | Install
  package:
    name: ntp
    state: present

- name: NTP | Configure service
  service:
    enabled: yes
    name: ntpd
    state: started
  when: 'not("/.dockerenv" is exists)'
