---
- name: NodeJS | Official repo key
  copy:
    dest: '/etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL'
    src: 'NODESOURCE-GPG-SIGNING-KEY-EL'
    mode: 0644

- name: NodeJS | Official repo
  yum_repository:
    baseurl: 'https://rpm.nodesource.com/pub_8.x/fc/$releasever/$basearch'
    description: 'Node.js Packages for Fedora Linux $releasever - $basearch'
    enabled: true
    failovermethod: 'priority'
    gpgcheck: true
    gpgkey: '/etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL'
    name: 'nodesource'
    state: present

- name: NodeJS | Install build packages
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'gcc-c++'
    - 'make'

- name: NodeJS | Install NodeJS
  package:
    name: 'nodejs'
    state: present
