---
# MongoDB
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/datastore/mongodb/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/prometheus/mongodb/main.yml'

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted

    - name: Restart Prometheus MongoDB Exporter
      service:
        name: prometheus-mongodb-exporter
        state: restarted


# PostgreSQL
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/datastore/postgresql/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/prometheus/postgresql/main.yml'

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql-10
        state: restarted

    - name: Restart Prometheus PostgreSQL Exporter
      service:
        name: prometheus-postgresql-exporter
        state: restarted
