---
# Datastores need docker0 interface to be up.
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/runtime/docker.yml'


# MongoDB
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/datastore/mongodb/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/prometheus/mongodb/main.yml'

  handlers:
    - name: Restart MongoDB
      service:
        name: mongod
        state: restarted
      when: 'not("/.dockerenv" is exists)'

    - name: Restart Prometheus MongoDB Exporter
      service:
        name: prometheus-mongodb-exporter
        state: restarted
      when: 'not("/.dockerenv" is exists)'


# PostgreSQL
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/datastore/postgresql/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/prometheus/postgresql/main.yml'

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql-10
        state: restarted
      when: 'not("/.dockerenv" is exists)'

    - name: Restart Prometheus PostgreSQL Exporter
      service:
        name: prometheus-postgresql-exporter
        state: restarted
      when: 'not("/.dockerenv" is exists)'
