---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/prometheus/server/main.yml'
    # TODO(stefano): prometheus node exporter
    # TODO(stefano): grafana

  handlers:
    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted
      when: 'not("/.dockerenv"|exists)'
