---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/monitoring/prometheus/server/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/prometheus/node/main.yml'
    - import_tasks: '../../tasks/infra/monitoring/grafana/main.yml'

  handlers:
    - name: Restart Prometheus
      service:
        name: prometheus
        state: restarted

    - name: Restart Prometheus Node Exporter
      service:
        name: prometheus-node-exporter
        state: restarted

    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
