---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/system/backup/main.yml'
    - import_tasks: '../../tasks/infra/system/email/main.yml'
    - import_tasks: '../../tasks/infra/system/ntp.yml'

  handlers:
    - name: 'Restart Postfix'
      service:
        name: postfix
        state: restarted

- hosts: m910q
  roles:
    - nickhammond.logrotate
