---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/infra/system/backup/main.yml'
    - import_tasks: '../../tasks/infra/system/email/main.yml'

  handlers:
    - name: 'Restart Postfix'
      service:
        name: postfix
        state: restarted
      when: 'not("/.dockerenv"|exists)'
