---
- name: NextCloud | Render dockerfile
  copy:
    dest: '/opt/nextcloud/{{ item }}'
    group: 'nextcloud'
    mode:  0644
    owner: 'nextcloud'
    src: '{{ item }}'
  with_items:
    - '000-default.conf'
    - 'apache2.conf'
    - 'Dockerfile'
    - 'ports.conf'

# The podman_image module does not support build arguments.
# Build the image with the command module instead.
- name: NextCloud | Look for image
  check_mode: false
  ignore_errors: true
  register: image_check
  command:
    argv:
      - 'podman'
      - 'image'
      - 'inspect'
      - '--format'
      - 'found'
      - 'nextcloud-custom:17.0.2'

- name: NextCloud | Build image
  when: image_check.rc != 0
  command:
    argv:
      - 'podman'
      - 'build'
      - '--force-rm'
      - '--rm'
      - '--tag=nextcloud-custom:17.0.2'
      - '--pull'
      - '--quiet'
      - '--build-arg'
      - 'GROUP_ID={{ nextcloud_group_id }}'
      - '--build-arg'
      - 'USER_ID={{ nextcloud_user_id }}'
      - '/opt/nextcloud'
  notify:
    - Restart NextCloud
