---
- name: NextCloud | Render dockerfile
  copy:
    dest: '/opt/nextcloud/{{ item }}'
    group: 'nextcloud'
    mode:  0644
    owner: 'nextcloud'
    src: '{{ item }}'
  with_items:
    - '000-default.conf'
    - 'apache2.conf'
    - 'Dockerfile'
    - 'ports.conf'

- name: NextCloud | Build image
  docker_image:
    build:
      args:
        GROUP_ID: '{{ nextcloud_group_id }}'
        USER_ID:  '{{ nextcloud_user_id }}'
      path: '/opt/nextcloud'
      pull: yes
    name: 'nextcloud-custom'
    rm: true
    source: build
    state: present
    tag: '17.0.2'
  when: 'not("/.dockerenv" is exists)'
  notify:
    - Restart NextCloud
