---
- name: NextCloud | Install
  import_tasks: 'install.yml'

- name: NextCloud | Container Image
  import_tasks: 'container-image.yml'

- name: NextCloud | Render systemd service unit
  copy:
    dest:  '/etc/systemd/system/nextcloud.service'
    src:   'nextcloud.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart NextCloud

- name: NextCloud | Render systemd timer units
  copy:
    dest:  '/etc/systemd/system/{{ item }}'
    src:   '{{ item }}'
    group: 'root'
    owner: 'root'
    mode:   0644
  with_items:
    - 'nextcloud-cron.service'
    - 'nextcloud-cron.timer'

- name: NextCloud | Service configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nextcloud
    state: started

- name: NextCloud | Cron Timer configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nextcloud-cron.timer
    state: started
