---
- name: NextCloud | Install
  import_tasks: 'install.yml'

- name: NextCloud | Container Image
  import_tasks: 'container-image.yml'

- name: NextCloud | Configure cron job
  copy:
    dest: '/etc/cron.d/nextcloud'
    mode: 0644
    content: |
      SHELL=/bin/sh
      PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      MAILTO={{ acmetool_email }}
      */15 * * * * root podman exec nextcloud.service php -f /var/www/html/cron.php

- name: NextCloud | Render systemd unit
  copy:
    dest:  '/etc/systemd/system/nextcloud.service'
    src:   'nextcloud.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart NextCloud

- name: NextCloud | Service configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nextcloud
    state: started
