---
- name: PostgreSQL | Render systemd unit
  copy:
    dest:  '/etc/systemd/system/postgresql-10.service'
    src:   'postgresql-10.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart PostgreSQL

- name: PostgreSQL | Configure Service
  service:
    enabled: yes
    name: postgresql-10
    state: started
  when: 'not("/.dockerenv" is exists)'

