---
- name: PostgreSQL | Render systemd unit
  copy:
    dest:  '/etc/systemd/system/postgresql-10.service'
    src:   'postgresql-10.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart PostgreSQL

- name: PostgreSQL | Configure Service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: postgresql-10
    state: started

