---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/runtime/podman.yml'
    - import_tasks: '../../tasks/app/firefly-iii/main.yml'

  handlers:
    - name: Restart FireFly-III
      service:
        name: firefly-iii
        state: restarted
