---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/runtime/podman.yml'
    - import_tasks: '../../tasks/app/nextcloud/main.yml'

  handlers:
    - name: Restart NextCloud
      service:
        name: nextcloud
        state: restarted
