---
- hosts: m910q
  tasks:
    - import_tasks: '../../tasks/runtime/docker.yml'
    - import_tasks: '../../tasks/app/wekan/main.yml'

  handlers:
    - name: Restart Wekan
      service:
        name: wekan
        state: restarted
      when: 'not("/.dockerenv"|exists)'
