---
- name: Email | Install Postfix
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - cyrus-sasl
    - cyrus-sasl-plain
    - postfix
  notify:
    - 'Restart Postfix'

- name: Email | Postfix main configuration
  template:
    dest: '/etc/postfix/main.cf'
    mode: 0644
    src: 'postfix.main.cf'
  notify:
    - 'Restart Postfix'

- name: Email | Postfix Sasl Password
  template:
    dest: '/etc/postfix/sasl_passwd'
    group: 'root'
    mode:  0600
    owner: 'root'
    src: 'sasl_passwd'
  notify:
    - 'Restart Postfix'

- name: Email | Postfix Sasl Remap
  command: postmap hash:/etc/postfix/sasl_passwd

- name: Email | Postfix Sasl Secure
  file:
    state: 'file'
    group: 'root'
    mode:  0600
    owner: 'root'
    path: '/etc/postfix/sasl_passwd.db'

- name: Email | Configure Postfix service
  service:
    enabled: yes
    name: postfix
    state: started
  when: 'not("/.dockerenv" is exists)'
