---
- name: Prometheus | PostgreSQL Exporter | Fetch archive
  get_url:
    url: 'https://github.com/wrouesnel/postgres_exporter/releases/download/v0.4.1/postgres_exporter_v0.4.1_linux-amd64.tar.gz'
    dest: '/opt/prometheus/archives/postgres_exporter_v0.4.1_linux-amd64.tar.gz'
    checksum: 'sha256:219c2c116cb496d54ddbd23f392a38c3496ab8e7118dfbf8b7c0b21593dedbfd'
    mode: 0644

- name: Prometheus | PostgreSQL Exporter | Extract the release
  unarchive:
    remote_src: yes
    dest: '/opt/prometheus/bin'
    src: '/opt/prometheus/archives/postgres_exporter_v0.4.1_linux-amd64.tar.gz'

- name: Prometheus | PostgreSQL Exporter | Activate the current version
  file:
    path: '/opt/prometheus/bin/postgres_exporter'
    src: '/opt/prometheus/bin/postgres_exporter_v0.4.1_linux-amd64/postgres_exporter'
    state: link
  notify:
    - Restart Prometheus PostgreSQL Exporter

- name: Prometheus | PostgreSQL Exporter | Render run script
  copy:
    dest: '/opt/prometheus/bin/run-postgresql-exporter'
    src:  'run-postgresql-exporter'
    group: 'prometheus'
    owner: 'prometheus'
    mode:  0755
  notify:
    - Restart Prometheus PostgreSQL Exporter
