global:
  scrape_interval: 15s


scrape_configs:
  - job_name: prometheus
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: node
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9100'

  - job_name: grafana
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:3000'
