# {{ ansible_managed }}
global:
  scrape_interval: 15s


scrape_configs:
  - job_name: authgateway
    metrics_path: '/api/proxied/metrics'
    static_configs:
      - targets:
        - 'localhost:8090'

  - job_name: grafana
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:3000'

  - job_name: mongodb
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9216'

  - job_name: node
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9100'

  - job_name: postgres
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9187'

  - job_name: prometheus
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: thermal
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'localhost:9300'
