---
- name: AuthGateway | Auditor | Install VirtualEnv
  package:
    name: python3-virtualenv
    state: present

- name: AuthGateway | Auditor | Create VirtualEnv
  pip:
    name: 'eve'
    state: present
    version: '0.9.2'
    virtualenv: '{{ authgateway_install_path }}/auditor'
    virtualenv_command: 'virtualenv'
    virtualenv_python: python3

- name: AuthGateway | Auditor | Render SystemD unit
  template:
    dest:  '/etc/systemd/system/authgateway-auditor.service'
    src:   'authgateway-auditor.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart AuthGateway Auditor

- name: AuthGateway | Auditor | Configure Service
  service:
    enabled: yes
    name: authgateway-auditor
    state: started
  when: 'not("/.dockerenv" is exists)'
