---
- name: LogRotate | SELinux | Install Ansible Helpers
  package:
    name: '{{ item }}'
    state: present
  with_items:
    - 'libselinux-python3'
    - 'policycoreutils-python3'

- name: LogRotate | SELinux | Persist nginx directory context
  sefcontext:
    setype: 'var_log_t'
    seuser: 'system_u'
    state:  present
    target: '{{ item }}'
  with_items:
    - '/opt/authgateway/http_proxy'
    - '/opt/authgateway/http_proxy/access.log'

- name: LogRotate | SELinux | Mock nginx logs.
  file:
    path: '/opt/authgateway/http_proxy/access.log'
    state: touch
  when: acme_skip_gen_certs is defined

- name: LogRotate | SELinux | Set nignx context
  file:
    path: '{{ item }}'
    setype: 'var_log_t'
  with_items:
    - '/opt/authgateway/http_proxy'
    - '/opt/authgateway/http_proxy/access.log'
