---
- name: AcmeTool | Enable copr repo
  command: dnf copr enable hlandau/acmetool --assumeyes
  args:
    creates: /etc/yum.repos.d/_copr_hlandau-acmetool.repo
    warn: false

- name: AcmeTool | Install
  package:
    name: acmetool
    state: present
