---
- name: Grafana | Data directory
  file:
    path: '/data/grafana'
    state: directory
    group: 'grafana'
    owner: 'grafana'
    mode:  0755

- name: Grafana | Configuration
  template:
    dest:  '/etc/grafana/grafana.ini'
    group: 'grafana'
    owner: 'grafana'
    mode:  0640
    src:   'grafana.ini'
  notify:
    - Restart Grafana
