---
- name: Wekan | Render systemd unit
  template:
    dest:  '/etc/systemd/system/wekan.service'
    src:   'wekan.service'
    group: 'root'
    owner: 'root'
    mode:   0644
  notify:
    - Restart Wekan

- name: Wekan | Service configuration
  systemd:
    daemon_reload: yes
    enabled: yes
    name: wekan
    state: started
